# Generated by Django 5.0 on 2026-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
