# Generated by Django 5.0 on 2026-10-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
    ]
